#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

git add .
cp -r ./src/fonts ./dist/cjs/fonts && cp -r ./src/fonts ./dist/esm/fonts
cp -r ./src/config ./dist/cjs/config && cp -r ./src/config ./dist/esm/config

# npm precommit
